/* Generated by bin2c, do not edit manually */

/* Contents of file test_io.bin */
#define test_io_bin_size 9
const unsigned char test_io_bin[9] = {
    0xB0, 0x10, 0xE6, 0x20, 0xB8, 0x00, 0x00, 0xEB, 0xFB
};
